Repository ripe-tech/ripe-registry-api-js, pull requests merged in 2020-09, with the labels that each got.

#4 Fix request method
  js/client.js
  js/iteration.js
  js/project.js
Labels: bug

#6 Fix client documentation
  js/client.js
Labels: bug, documentation

#5 Update to use nested iteration endpoints
  js/base.js
  js/index.js
  js/iteration.js
  js/project.js
  types/index.d.ts
  types/iteration.d.ts
  types/project.d.ts
  vercel.json
Labels: enhancement, fast-track

#7 Support for options argument in list methods
  js/client.js
  js/person.js
  js/project.js
Labels: enhancement
